[package]
name = "main000a"
version = "0.1.0"
authors = ["wartyz <zwenderk@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libfinal = { path = "../../libfinal/" }
perlin_noise = "1.0.1"
